repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.92.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_tflint
      additional_dependencies: [tflint]
    - id: terraform_docs
      additional_dependencies: [terraform-docs]
    - id: terraform_trivy
      additional_dependencies: [trivy]
